"""Career & Placement content for the Sayyed EdVantage Study Portal.

Question banks, readiness checklists and job-platform links. No invented jobs,
drives or placements — the Job Board is an application tracker plus links to
real job platforms.
"""

SUBJECTS = [
    {"id": "python", "name": "Python Programming"},
    {"id": "data-science", "name": "Data Science"},
    {"id": "ai-genai", "name": "AI & Generative AI"},
    {"id": "data-analytics", "name": "Data Analytics"},
    {"id": "linux", "name": "Linux Administration"},
    {"id": "devops", "name": "DevOps"},
    {"id": "cyber", "name": "Cyber Security & Ethical Hacking"},
]

# Each question: q, keywords (for fallback scoring), level, type.
QUESTIONS = {
    "python": [
        {"q": "What is the difference between a list and a tuple in Python? When would you use each?",
         "keywords": ["mutable", "immutable", "ordered", "list", "tuple"], "level": "beginner", "type": "technical"},
        {"q": "Explain list comprehension with an example. How is it different from a for loop?",
         "keywords": ["comprehension", "concise", "loop", "list", "example"], "level": "beginner", "type": "technical"},
        {"q": "What is the difference between `==` and `is` in Python?",
         "keywords": ["value", "equality", "identity", "object", "memory"], "level": "beginner", "type": "technical"},
        {"q": "How does exception handling work in Python? Explain try, except, else and finally.",
         "keywords": ["try", "except", "finally", "error", "exception", "handle"], "level": "beginner", "type": "technical"},
        {"q": "What are `*args` and `**kwargs`? Give a practical example.",
         "keywords": ["arguments", "variable", "tuple", "dictionary", "function", "unpack"], "level": "intermediate", "type": "technical"},
        {"q": "What are decorators in Python? Describe a real use case.",
         "keywords": ["decorator", "function", "wrapper", "logging", "authentication", "@"], "level": "intermediate", "type": "technical"},
        {"q": "What are generators and the `yield` keyword? Why are they memory efficient?",
         "keywords": ["generator", "yield", "lazy", "memory", "iterator", "efficient"], "level": "intermediate", "type": "technical"},
        {"q": "Explain the difference between a shallow copy and a deep copy, with an example.",
         "keywords": ["shallow", "deep", "copy", "reference", "nested", "copy module"], "level": "intermediate", "type": "technical"},
        {"q": "What is the GIL in Python and how does it affect multithreading?",
         "keywords": ["gil", "global interpreter lock", "thread", "multithreading", "concurrency", "cpu"], "level": "advanced", "type": "technical"},
        {"q": "What is a context manager and how does the `with` statement work?",
         "keywords": ["context manager", "with", "enter", "exit", "resource", "file"], "level": "intermediate", "type": "technical"},
        {"q": "How would you debug a Python program that is running slowly? Walk me through your approach.",
         "keywords": ["profile", "cprofile", "bottleneck", "optimize", "algorithm", "measure"], "level": "advanced", "type": "technical"},
        {"q": "Tell me about a Python project you built. What was the hardest bug you faced and how did you fix it?",
         "keywords": ["project", "bug", "debug", "fix", "learn", "built"], "level": "beginner", "type": "hr"},
    ],
    "data-science": [
        {"q": "What is the difference between supervised and unsupervised learning? Give one example of each.",
         "keywords": ["supervised", "unsupervised", "labeled", "classification", "clustering"], "level": "beginner", "type": "technical"},
        {"q": "What is overfitting? How do you detect and prevent it?",
         "keywords": ["overfitting", "generalization", "regularization", "cross-validation", "training", "test"], "level": "beginner", "type": "technical"},
        {"q": "Explain the bias-variance tradeoff in simple terms.",
         "keywords": ["bias", "variance", "tradeoff", "underfitting", "overfitting", "complexity"], "level": "intermediate", "type": "technical"},
        {"q": "What is cross-validation and why do we use it instead of a single train-test split?",
         "keywords": ["cross-validation", "folds", "k-fold", "robust", "evaluation", "split"], "level": "intermediate", "type": "technical"},
        {"q": "What is the difference between classification and regression? Give real examples.",
         "keywords": ["classification", "regression", "categories", "continuous", "predict", "example"], "level": "beginner", "type": "technical"},
        {"q": "How do you handle missing data in a dataset? What factors guide your choice?",
         "keywords": ["missing", "imputation", "drop", "mean", "median", "null"], "level": "intermediate", "type": "technical"},
        {"q": "What is feature scaling? When is it necessary and when can you skip it?",
         "keywords": ["scaling", "normalization", "standardization", "gradient", "distance", "svm", "knn"], "level": "intermediate", "type": "technical"},
        {"q": "Explain precision vs recall. In what situation would you prioritise recall over precision?",
         "keywords": ["precision", "recall", "false positive", "false negative", "medical", "fraud"], "level": "intermediate", "type": "technical"},
        {"q": "What is a confusion matrix and what does each cell tell you?",
         "keywords": ["confusion matrix", "true positive", "false positive", "true negative", "false negative"], "level": "beginner", "type": "technical"},
        {"q": "What is the difference between bagging and boosting? Name one algorithm for each.",
         "keywords": ["bagging", "boosting", "random forest", "xgboost", "ensemble", "parallel", "sequential"], "level": "advanced", "type": "technical"},
        {"q": "A company wants to predict which customers will cancel their subscription. Walk me through how you would approach this end to end.",
         "keywords": ["churn", "data", "features", "model", "evaluation", "deploy", "business"], "level": "advanced", "type": "technical"},
        {"q": "Describe a data project you worked on from raw data to final insight. What did you learn?",
         "keywords": ["project", "data", "cleaning", "analysis", "insight", "learn"], "level": "beginner", "type": "hr"},
    ],
    "ai-genai": [
        {"q": "What is a transformer? What are its key components?",
         "keywords": ["transformer", "attention", "encoder", "decoder", "self-attention"], "level": "intermediate", "type": "technical"},
        {"q": "What is the difference between GPT-style (decoder-only) and BERT-style (encoder-only) models?",
         "keywords": ["gpt", "bert", "decoder", "encoder", "generative", "understanding", "bidirectional"], "level": "intermediate", "type": "technical"},
        {"q": "What is prompt engineering? Name three techniques that improve LLM outputs.",
         "keywords": ["prompt", "few-shot", "chain-of-thought", "role", "instructions", "examples"], "level": "beginner", "type": "technical"},
        {"q": "What are embeddings and how are they used in a RAG system?",
         "keywords": ["embeddings", "vector", "semantic", "retrieval", "similarity", "rag"], "level": "intermediate", "type": "technical"},
        {"q": "What is RAG (Retrieval-Augmented Generation)? When would you choose it over fine-tuning?",
         "keywords": ["rag", "retrieval", "documents", "fine-tuning", "knowledge", "hallucination"], "level": "intermediate", "type": "technical"},
        {"q": "Compare fine-tuning, RAG and prompt engineering. What are the tradeoffs of each?",
         "keywords": ["fine-tuning", "rag", "prompt", "cost", "data", "tradeoff", "control"], "level": "advanced", "type": "technical"},
        {"q": "What does the temperature parameter do in LLM sampling? What happens at very high vs very low values?",
         "keywords": ["temperature", "randomness", "sampling", "creativity", "deterministic"], "level": "beginner", "type": "technical"},
        {"q": "What is hallucination in LLMs and what are practical ways to reduce it?",
         "keywords": ["hallucination", "grounding", "rag", "citations", "verification", "factual"], "level": "intermediate", "type": "technical"},
        {"q": "What are tokens and context windows? Why do they matter when building LLM apps?",
         "keywords": ["tokens", "context window", "limit", "cost", "truncation", "chunking"], "level": "beginner", "type": "technical"},
        {"q": "Explain chain-of-thought prompting. Why does asking a model to reason step by step help?",
         "keywords": ["chain-of-thought", "reasoning", "step by step", "complex", "accuracy"], "level": "intermediate", "type": "technical"},
        {"q": "What are AI agents? Describe an example workflow where an agent completes a multi-step task.",
         "keywords": ["agent", "tools", "planning", "autonomous", "workflow", "steps", "llm"], "level": "advanced", "type": "technical"},
        {"q": "What excites you most about generative AI, and where do you see it going in the next 3 years?",
         "keywords": ["excited", "future", "genai", "opportunity", "learn", "impact"], "level": "beginner", "type": "hr"},
    ],
    "data-analytics": [
        {"q": "What is the difference between WHERE and HAVING in SQL?",
         "keywords": ["where", "having", "filter", "rows", "groups", "aggregation", "group by"], "level": "beginner", "type": "technical"},
        {"q": "Explain the different types of JOINs in SQL with a simple example.",
         "keywords": ["join", "inner", "left", "right", "full", "outer", "keys"], "level": "beginner", "type": "technical"},
        {"q": "What is the difference between a primary key and a foreign key?",
         "keywords": ["primary key", "foreign key", "unique", "reference", "relationship", "table"], "level": "beginner", "type": "technical"},
        {"q": "How would you find duplicate rows in a table using SQL?",
         "keywords": ["duplicate", "group by", "having", "count", "distinct"], "level": "intermediate", "type": "technical"},
        {"q": "In pandas, what is the difference between merge and concat?",
         "keywords": ["pandas", "merge", "concat", "join", "keys", "axis", "dataframe"], "level": "intermediate", "type": "technical"},
        {"q": "How do you detect and handle outliers in a dataset?",
         "keywords": ["outliers", "iqr", "z-score", "boxplot", "remove", "cap", "investigate"], "level": "intermediate", "type": "technical"},
        {"q": "What makes a good dashboard? What mistakes do beginners make?",
         "keywords": ["dashboard", "kpi", "clear", "audience", "clutter", "visualization", "actionable"], "level": "intermediate", "type": "technical"},
        {"q": "Explain GROUP BY with an aggregate function using a real example.",
         "keywords": ["group by", "sum", "count", "average", "aggregation", "categories"], "level": "beginner", "type": "technical"},
        {"q": "What is the difference between correlation and causation? Why does it matter in analytics?",
         "keywords": ["correlation", "causation", "relationship", "cause", "confounding", "experiments"], "level": "intermediate", "type": "technical"},
        {"q": "What is a KPI? Give three KPIs you would track for an e-commerce business.",
         "keywords": ["kpi", "metric", "conversion", "revenue", "retention", "aov", "churn"], "level": "beginner", "type": "technical"},
        {"q": "Sales dropped 20% last month. How would you investigate and present your findings to a non-technical manager?",
         "keywords": ["investigate", "segment", "trend", "hypothesis", "data", "present", "simple", "recommend"], "level": "advanced", "type": "technical"},
        {"q": "Walk me through an analysis project you are proud of. What was the business impact?",
         "keywords": ["project", "analysis", "insight", "impact", "business", "proud"], "level": "beginner", "type": "hr"},
    ],
    "linux": [
        {"q": "How do you check disk usage and find which files or folders are taking the most space?",
         "keywords": ["df", "du", "disk", "usage", "sort", "large files"], "level": "beginner", "type": "technical"},
        {"q": "Explain Linux file permissions: what do rwx mean, and how do chmod and chown work?",
         "keywords": ["permissions", "rwx", "chmod", "chown", "read", "write", "execute", "owner"], "level": "beginner", "type": "technical"},
        {"q": "What is the difference between `ps`, `top` and `htop`?",
         "keywords": ["ps", "top", "htop", "processes", "monitor", "cpu", "memory"], "level": "beginner", "type": "technical"},
        {"q": "How do you manage services on a modern Linux system? Explain systemctl with examples.",
         "keywords": ["systemctl", "systemd", "service", "start", "stop", "enable", "status"], "level": "intermediate", "type": "technical"},
        {"q": "What is SSH key-based authentication and how do you set it up?",
         "keywords": ["ssh", "key", "public", "private", "authorized_keys", "ssh-keygen", "passwordless"], "level": "intermediate", "type": "technical"},
        {"q": "A service crashed at 2 AM. How would you investigate using logs?",
         "keywords": ["journalctl", "logs", "var/log", "systemctl status", "timestamp", "investigate"], "level": "intermediate", "type": "technical"},
        {"q": "How do you schedule a script to run every day at midnight? Explain cron syntax.",
         "keywords": ["cron", "crontab", "schedule", "0 0", "syntax", "recurring"], "level": "beginner", "type": "technical"},
        {"q": "How do you allow or block network traffic on Linux? Explain with ufw or firewalld.",
         "keywords": ["firewall", "ufw", "firewalld", "port", "allow", "deny", "iptables"], "level": "intermediate", "type": "technical"},
        {"q": "What is the difference between a hard link and a soft (symbolic) link?",
         "keywords": ["hard link", "soft link", "symbolic", "inode", "ln", "pointer"], "level": "intermediate", "type": "technical"},
        {"q": "How do you find which process is listening on a specific port?",
         "keywords": ["ss", "netstat", "lsof", "port", "listening", "process", "pid"], "level": "intermediate", "type": "technical"},
        {"q": "A server is running out of memory. Walk me through how you diagnose and respond.",
         "keywords": ["memory", "free", "oom", "top", "swap", "process", "kill", "leak"], "level": "advanced", "type": "technical"},
        {"q": "Describe a time you troubleshot a real problem on a Linux machine. What was your process?",
         "keywords": ["troubleshoot", "problem", "logs", "diagnose", "fix", "process", "learn"], "level": "beginner", "type": "hr"},
    ],
    "devops": [
        {"q": "What is CI/CD? Describe the stages of a typical pipeline.",
         "keywords": ["ci", "cd", "pipeline", "build", "test", "deploy", "automation", "continuous"], "level": "beginner", "type": "technical"},
        {"q": "What is the difference between a Docker image and a container?",
         "keywords": ["docker", "image", "container", "template", "running", "instance", "layer"], "level": "beginner", "type": "technical"},
        {"q": "What is a Dockerfile? Explain the key instructions with an example.",
         "keywords": ["dockerfile", "from", "run", "copy", "cmd", "expose", "workdir", "build"], "level": "intermediate", "type": "technical"},
        {"q": "Explain blue-green deployment vs canary deployment. When would you use each?",
         "keywords": ["blue-green", "canary", "deployment", "rollback", "traffic", "risk", "gradual"], "level": "intermediate", "type": "technical"},
        {"q": "What is Kubernetes? Explain pods, deployments and services.",
         "keywords": ["kubernetes", "pod", "deployment", "service", "orchestration", "cluster", "scaling"], "level": "intermediate", "type": "technical"},
        {"q": "How should secrets (API keys, passwords) be managed in CI/CD pipelines?",
         "keywords": ["secrets", "vault", "environment variables", "encrypted", "never commit", "rotation"], "level": "intermediate", "type": "technical"},
        {"q": "What is Infrastructure as Code? Name two tools and their use cases.",
         "keywords": ["infrastructure as code", "terraform", "ansible", "versioned", "repeatable", "automation"], "level": "intermediate", "type": "technical"},
        {"q": "What is the difference between `git merge` and `git rebase`?",
         "keywords": ["git", "merge", "rebase", "history", "branch", "conflict", "linear"], "level": "beginner", "type": "technical"},
        {"q": "How do you monitor applications in production? What do you alert on?",
         "keywords": ["monitoring", "metrics", "logs", "alerts", "prometheus", "grafana", "uptime", "latency"], "level": "advanced", "type": "technical"},
        {"q": "What is a reverse proxy? Why would you put nginx in front of your app?",
         "keywords": ["reverse proxy", "nginx", "load balancing", "ssl", "caching", "routing"], "level": "intermediate", "type": "technical"},
        {"q": "You push code to main and the deployment fails halfway. Walk me through your response.",
         "keywords": ["rollback", "logs", "pipeline", "investigate", "fix", "test", "communicate"], "level": "advanced", "type": "technical"},
        {"q": "Tell me about a deployment that went wrong. What happened and what did you learn?",
         "keywords": ["deployment", "wrong", "incident", "learn", "postmortem", "fix"], "level": "beginner", "type": "hr"},
    ],
    "cyber": [
        {"q": "Explain the CIA triad in cybersecurity.",
         "keywords": ["cia", "confidentiality", "integrity", "availability", "triad"], "level": "beginner", "type": "technical"},
        {"q": "What is the difference between symmetric and asymmetric encryption? Give examples.",
         "keywords": ["symmetric", "asymmetric", "aes", "rsa", "key", "public", "private"], "level": "beginner", "type": "technical"},
        {"q": "What is SQL injection? How does it work and how do you prevent it?",
         "keywords": ["sql injection", "input", "parameterized", "prepared statements", "sanitize", "query"], "level": "intermediate", "type": "technical"},
        {"q": "What is Cross-Site Scripting (XSS)? Name its types and how to defend against it.",
         "keywords": ["xss", "cross-site scripting", "reflected", "stored", "dom", "escape", "csp"], "level": "intermediate", "type": "technical"},
        {"q": "What is the difference between a vulnerability, a threat and a risk?",
         "keywords": ["vulnerability", "threat", "risk", "weakness", "attacker", "impact", "likelihood"], "level": "beginner", "type": "technical"},
        {"q": "What happens during the TCP three-way handshake? Why does it matter for port scanning?",
         "keywords": ["tcp", "syn", "syn-ack", "ack", "handshake", "scanning", "nmap"], "level": "intermediate", "type": "technical"},
        {"q": "What is the difference between a firewall, an IDS and an IPS?",
         "keywords": ["firewall", "ids", "ips", "detection", "prevention", "intrusion", "block", "alert"], "level": "intermediate", "type": "technical"},
        {"q": "How does a phishing attack work, and what are the best defences for an organisation?",
         "keywords": ["phishing", "email", "social engineering", "training", "mfa", "verify", "awareness"], "level": "beginner", "type": "technical"},
        {"q": "What is privilege escalation? Give one example each of vertical and horizontal escalation.",
         "keywords": ["privilege escalation", "vertical", "horizontal", "admin", "root", "access"], "level": "advanced", "type": "technical"},
        {"q": "What is the difference between black-box, white-box and grey-box penetration testing?",
         "keywords": ["black-box", "white-box", "grey-box", "knowledge", "pentest", "scope"], "level": "intermediate", "type": "technical"},
        {"q": "During an assessment you discover a client's cloud storage bucket is publicly readable. What do you do, step by step?",
         "keywords": ["disclosure", "responsible", "document", "notify", "scope", "evidence", "ethics"], "level": "advanced", "type": "technical"},
        {"q": "Why do you want to work in cybersecurity? How do you view the ethics of hacking?",
         "keywords": ["ethics", "curiosity", "defend", "responsible", "white-hat", "passion", "learn"], "level": "beginner", "type": "hr"},
    ],
}

GENERAL_CHECKLIST = [
    "Resume is complete, ATS-friendly and proofread",
    "LinkedIn profile is complete with a professional photo",
    "2+ portfolio projects with clear descriptions",
    "Scored 7+ in at least one AI mock interview",
    "Can explain every skill listed on the resume confidently",
    "Applied to 10+ relevant jobs or internships",
]

SUBJECT_CHECKLISTS = {
    "python": [
        "Built 3+ Python scripts or mini-projects",
        "Comfortable with OOP: classes, inheritance, methods",
        "Can solve easy–medium coding problems independently",
        "Knows pip, virtualenv and requirements files",
        "Git basics: clone, commit, push, pull requests",
        "Has debugged real tracebacks without help",
    ],
    "data-science": [
        "Completed an end-to-end ML project (data → model → evaluation)",
        "Comfortable with pandas, NumPy and scikit-learn",
        "Can explain overfitting, cross-validation and key metrics",
        "Built at least one data visualisation story",
        "Knows basic statistics: distributions, hypothesis testing",
        "Can present model results to a non-technical audience",
    ],
    "ai-genai": [
        "Built a project using an LLM API (chat, summariser, bot)",
        "Understands prompts, tokens and context windows",
        "Can explain RAG and has tried a simple RAG setup",
        "Knows embeddings and vector search basics",
        "Aware of hallucinations and how to reduce them",
        "Follows AI safety and responsible-use practices",
    ],
    "data-analytics": [
        "Can write JOINs, GROUP BY and subqueries in SQL fluently",
        "Comfortable cleaning data with pandas or Excel",
        "Built 2+ dashboards or analytical reports",
        "Can choose the right chart for the message",
        "Understands KPIs and basic business metrics",
        "Can explain an analysis to a non-technical stakeholder",
    ],
    "linux": [
        "Comfortable navigating the terminal: files, permissions, processes",
        "Can manage services with systemctl and read logs",
        "Set up SSH key-based login on a server",
        "Can schedule jobs with cron",
        "Basic networking: ports, firewall rules, DNS checks",
        "Has troubleshot a real Linux issue end to end",
    ],
    "devops": [
        "Can containerise an app with Docker (Dockerfile + compose)",
        "Understands CI/CD and has used GitHub Actions or similar",
        "Git workflows: branches, merges, pull requests",
        "Knows Kubernetes basics: pods, deployments, services",
        "Can set up basic monitoring and alerts",
        "Practises secret management (never commits secrets)",
    ],
    "cyber": [
        "Understands networking basics: TCP/IP, DNS, HTTP",
        "Can explain OWASP Top 10 vulnerabilities",
        "Has practised legally on labs (TryHackMe / HackTheBox)",
        "Knows Linux command line confidently",
        "Understands encryption basics and password security",
        "Committed to ethical, legal hacking practices",
    ],
}

JOB_PLATFORMS = [
    {"name": "Naukri.com", "url": "https://www.naukri.com", "note": "India's largest job portal"},
    {"name": "LinkedIn Jobs", "url": "https://www.linkedin.com/jobs", "note": "Jobs + networking"},
    {"name": "Indeed", "url": "https://www.indeed.co.in", "note": "Global listings, fresher-friendly filters"},
    {"name": "Foundit (Monster)", "url": "https://www.foundit.in", "note": "Indian job listings"},
]

JOB_STATUSES = ["Wishlist", "Applied", "Screening", "Interview", "Offer", "Rejected"]
