
import os,sys,tempfile,json,copy
sys.path.insert(0,os.path.dirname(__file__))
from Sayyed_EdVantage_PHASE4_INTEGRATION02 import *
def check(n,c):
    if not c: raise AssertionError(n)
    print("PASS:",n)
root=tempfile.mkdtemp(); os.makedirs(os.path.join(root,"data"))
with open(os.path.join(root,"data","leads.json"),"w",encoding="utf-8") as f:
    json.dump({"leads":[{"lead_id":"SE-00001","course_id":"SE-DS-001","region":"India","stage":"Interested"},{"lead_id":"SE-00002","course_id":"SE-PY-001","region":"India","stage":"New"}]},f)
p=ConversationCRMDecisionPipeline(root)
check("execution disabled",not p.execution_enabled); check("messaging disabled",not p.messaging_enabled)
check("CRM writes disabled",not p.crm_writes_enabled); check("external disabled",not p.external_actions_enabled)
check("executor disabled",not p.executor_invocation_enabled); check("fail closed",p.fail_closed)
r=p.run_turn("S1","Tell me about Data Science","SE-00001")
check("initial ready",r.status==STATUS_READY); check("initial course",r.course_ids==["SE-DS-001"]); check("initial CRM verified",r.crm_verified); check("initial no context reuse",not r.context_reused)
r=p.run_turn("S1","What is the fee?")
check("follow-up ready",r.status==STATUS_READY); check("follow-up course",r.course_ids==["SE-DS-001"]); check("context reused",r.context_reused); check("fee grounded","₹50,000" in r.response_text)
r=p.run_turn("S1","Will it guarantee me a job?")
check("context career ready",r.status==STATUS_READY); check("career safety","does not guarantee" in r.response_text)
r=p.run_turn("S2","What is the fee?","SE-00002")
check("CRM course reuse",r.course_ids==["SE-PY-001"]); check("CRM course provenance","CRM_READ" in r.provenance)
r=p.run_turn("S3","Data Science and Python fees?")
check("multi clarification",r.status==STATUS_CLARIFY); check("multi preserved",set(r.course_ids)=={"SE-DS-001","SE-PY-001"})
r=p.run_turn("S4","Which course is best?")
check("recommend clarification",r.status==STATUS_CLARIFY)
r=p.run_turn("S5","Can I get a discount on Data Science?","SE-00001")
check("discount review",r.status==STATUS_REVIEW); check("review handoff",r.human_handoff_required)
r=p.run_turn("S6","What is the international Data Science fee?")
check("unknown region clarification",r.status==STATUS_CLARIFY); check("no India quote","₹50,000" not in r.response_text)
r=p.run_turn("S7","Tell me about certification for Data Science")
check("cert unknown safe",r.status==STATUS_READY); check("cert not invented","not currently defined" in r.response_text)
r=p.run_turn("S8","Tell me about Python","SE-99999")
check("invalid lead clarification",r.status==STATUS_CLARIFY); check("invalid lead error",bool(r.errors))
a=p.run_turn("A","Tell me about Python"); b=p.run_turn("B","What is the fee?")
check("session isolation",b.status==STATUS_CLARIFY)
r=p.run_turn("S1","Tell me about Python"); check("explicit override",r.course_ids==["SE-PY-001"])
r=p.run_turn("S1","What is the fee?"); check("override persists",r.course_ids==["SE-PY-001"]); check("python fee","₹35,000" in r.response_text)
r=p.run_turn("S9",""); check("empty safe",r.status==STATUS_CLARIFY)
r=p.run_turn("S10","Tell me about Linux"); check("validation clean",p.validate(r)==[])
bad=copy.deepcopy(r); bad.execution_authorized=True; check("validator catches execution",bool(p.validate(bad)))
bad=copy.deepcopy(r); bad.crm_writes_enabled=True; check("validator catches CRM",bool(p.validate(bad)))
bad=copy.deepcopy(r); bad.provenance=[]; check("validator catches provenance",bool(p.validate(bad)))
r=run_decision_pipeline("W","Tell me about DevOps",project_root=root); check("wrapper works",r.course_ids==["SE-DEVOPS-001"])
print("\nPHASE 4 INTEGRATION 02 TEST RESULT: ALL PASSED")
